spring:
  application:
    name: velocity-blueprint-cli
  main:
    banner-mode: off

velocity-blueprint:
  environment:
    workspaceDirectory: VelocityBlueprint
    modelDirectory: models
    templateDirectory: templates
